services:

  api:
    build: .
    depends_on:
      - cache_db
  
    networks:
      - net
    
    environment:
      OAUTH2_SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      OAUTH2_ALGORITHM: HS256
      GRPC_HOST: localhost
      GRPC_PORT: 3333
      CACHE_URL: redis://cache_db:6379

    command: ["python", "main.py"]

  cache_db:
    image: redis
    restart: always
    
    networks:
      - net


networks:
  net:
    driver: bridge